---
$schema: "http://json-schema.org/draft-07/schema#"

title: FastAPI schema
description: jsonschema for FastAPI connection

properties:
  fastapi:
    type: object
    properties:
      app:
        type: object
        properties:
          location:
            type: string
